### PR TITLE
Remove support to run the quickstart using an Inmanta server on Centos7

### PR DESCRIPTION
**Pull request by arnaudsjs**
This PR removes support to run the quickstart using an Inmanta server on Centos7. This change is required since we don't publish Centos7 RPMs anymore for inmanta-oss. 

Question: The agent containers are still using Centos7. Should I also migrate them to Centos8 or do we differ that to another ticket?

### CODE REVIEW

**Review by wouterdb — APPROVED** [review]
If it is not too difficult, I would upgrade the agents as well

**Comment by arnaudsjs** [comment]
> If it is not too difficult, I would upgrade the agents as well

I don't think it is. I will add the change.

**Review by FloLey — APPROVED** [review]

**Comment by arnaudsjs** [comment]
Migrating the slaves to Centos8 is going to take a lot more time than I expected. It seems that the `drupal7` package is not available on the `epel` repositories on Centos8. So we will have to change the drupal module in order to support Centos8 as well. I assume that we will postpone it then. I will create a ticket for this and include my findings in it.

**Comment by arnaudsjs** [comment]
I created the ticket #24

**Pull request merged**
